dead_letter_queue.enable: true
http.host: 0.0.0.0
http.port: 9600-9700
log.format: json
log.level: info
node.name: logstash
path.data: /usr/share/logstash/data
path.logs: /usr/share/logstash/logs
pipeline.batch.delay: 50
pipeline.batch.size: 500
pipeline.id: main
pipeline.unsafe_shutdown: false
pipeline.workers: 2
queue.checkpoint.writes: 1024
queue.max_bytes: 1gb
queue.type: persisted
xpack.monitoring.elasticsearch.hosts: http://elasticsearch:9200
xpack.monitoring.elasticsearch.password: Niraj@31
xpack.monitoring.elasticsearch.username: elastic
xpack.monitoring.enabled: true
